---
title: "Exercise 1"
description: |
  Test test test
---

Before we do any visualisations, we need to load and transform the data we'll use. Run the following chunks to get set up.

::: {.callout-tip}
If you accidentally close the R terminal, you can run these chunks again in a new one!
:::

```{r}
#| label: setup

library(tidyverse)
library(here)
```

```{r}
#| label: load-weather

weather <-
  read_csv(
    here("data", "weather", "HM01X_Data_086068_539639810394595.csv"),
    col_names = c("datetime", "temperature"),
    col_types = cols(
      col_skip(),
      col_datetime("%d/%m/%Y %H:%M"),
      col_double(),
      col_skip(),
      col_skip(),
      col_skip()),
    skip = 1)
```

```{r}
#| label: load-electricity

# note to mat - i'm not sure what these columns mean
# is bc the one i want?
electricity <-
  read_csv(
    here("data", "electricity", "citipower_2005_2017.csv"),
    # col_names = c("datetime", "temperature"),
    # col_types = cols(
    #   col_skip(),
    #   col_datetime("%d/%m/%Y %H:%M"),
    #   col_double(),
    #   col_skip(),
    #   col_skip(),
    #   col_skip()),
    # skip = 1,
    na = c("", "nan")) |>
  mutate(date = as.Date(`...1`)) |>
  group_by(date) |>
  summarise(mean_bc = mean(BC, na.rm = TRUE))
```